In [43]:
# Importar librerías
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import skew, kurtosis

In [ ]:
# Definición de la función para cálculo de los estadísticos

def descriptive_statistics(variable, nombre_variable):
    media = float(np.mean(variable))
    #promedio = float(np.average(variable))
    varianza = float(np.var(variable, ddof=1)) #varianza muestral
    desviacion_estandar = float(np.std(variable, ddof=1)) #desviación estándar muestral
    asimetria = float(skew(variable))
    curtosis = float(kurtosis(variable, fisher=False)) #Fisher kurtosis (excess kurtosis): normal = 0
    print(f'Análisis descriptivo de {nombre_variable}\Media: {media}\nVarianza: {varianza}\nDesviación estándar: {desviacion_estandar}\nAsimetría: {asimetria}\nCurtosis: {curtosis}'
      )

In [44]:
"""
Se carga el dataset de inflación de los alimentos, frecuencia mensual (fin de mes)
del 30 de noviembre de 2018 al 30 de noviembre de 2025.
"""

ds_inflacion = pd.read_excel('./data/Inflación_de_alimentos_Dato_fin_de_mes.xlsx')
ds_inflacion.head(5)

        Fecha Inflación de alimentos(Dato fin de mes)
0  dd/mm/aaaa                                       %
1  30/11/2018                                    1,61
2  31/12/2018                                    1,87
3  31/01/2019                                    2,07
4  28/02/2019                                    2,29

In [45]:
# Se eliminan registros nulos y la primera fila por contener caracteres diferentes a la fecha
ds_inflacion = ds_inflacion.dropna()
ds_inflacion = ds_inflacion.iloc[1:]
ds_inflacion.head(5)

        Fecha Inflación de alimentos(Dato fin de mes)
1  30/11/2018                                    1,61
2  31/12/2018                                    1,87
3  31/01/2019                                    2,07
4  28/02/2019                                    2,29
5  31/03/2019                                    3,24

In [46]:
# Asignación del formato fecha
ds_inflacion['Fecha'] = pd.to_datetime(ds_inflacion['Fecha'], dayfirst=True, errors='coerce')
ds_inflacion.head(5)

       Fecha Inflación de alimentos(Dato fin de mes)
1 2018-11-30                                    1,61
2 2018-12-31                                    1,87
3 2019-01-31                                    2,07
4 2019-02-28                                    2,29
5 2019-03-31                                    3,24

In [47]:
# Se eliminan los registros NaT/NaN
ds_inflacion[ds_inflacion['Fecha'].isna()]
ds_inflacion = ds_inflacion.dropna(subset = ['Fecha'])
ds_inflacion

        Fecha Inflación de alimentos(Dato fin de mes)
1  2018-11-30                                    1,61
2  2018-12-31                                    1,87
3  2019-01-31                                    2,07
4  2019-02-28                                    2,29
5  2019-03-31                                    3,24
..        ...                                     ...
80 2025-06-30                                    4,31
81 2025-07-31                                    4,94
82 2025-08-31                                    6,13
83 2025-09-30                                    6,21
84 2025-10-31                                    6,64

[84 rows x 2 columns]

In [48]:
ds_inflacion['Año'] = ds_inflacion['Fecha'].dt.year
ds_inflacion

        Fecha Inflación de alimentos(Dato fin de mes)   Año
1  2018-11-30                                    1,61  2018
2  2018-12-31                                    1,87  2018
3  2019-01-31                                    2,07  2019
4  2019-02-28                                    2,29  2019
5  2019-03-31                                    3,24  2019
..        ...                                     ...   ...
80 2025-06-30                                    4,31  2025
81 2025-07-31                                    4,94  2025
82 2025-08-31                                    6,13  2025
83 2025-09-30                                    6,21  2025
84 2025-10-31                                    6,64  2025

[84 rows x 3 columns]

In [ ]:
años = ds_inflacion['Año'].unique()